// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prn212.Models;

#nullable disable

namespace Prn212.Migrations
{
    [DbContext(typeof(Prn212Context))]
    [Migration("20250315063447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prn212.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HouseholdID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseholdId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("HeadOfHouseholdId")
                        .HasColumnType("int")
                        .HasColumnName("HeadOfHouseholdID");

                    b.HasKey("HouseholdId")
                        .HasName("PK__Househol__1453D6EC88FAEEB4");

                    b.HasIndex("HeadOfHouseholdId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Prn212.Models.HouseholdMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("int")
                        .HasColumnName("HouseholdID");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MemberId")
                        .HasName("PK__Househol__0CF04B3878DC97B7");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId");

                    b.ToTable("HouseholdMembers");
                });

            modelBuilder.Entity("Prn212.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__Logs__5E5499A8BFC78109");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Prn212.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32FE6A4C31");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Prn212.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegistrationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RegistrationId")
                        .HasName("PK__Registra__6EF5883026EEB188");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Prn212.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACEED80B31");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AC29BCAA")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Prn212.Models.Household", b =>
                {
                    b.HasOne("Prn212.Models.User", "HeadOfHousehold")
                        .WithMany("Households")
                        .HasForeignKey("HeadOfHouseholdId")
                        .HasConstraintName("FK__Household__HeadO__3C69FB99");

                    b.Navigation("HeadOfHousehold");
                });

            modelBuilder.Entity("Prn212.Models.HouseholdMember", b =>
                {
                    b.HasOne("Prn212.Models.Household", "Household")
                        .WithMany("HouseholdMembers")
                        .HasForeignKey("HouseholdId")
                        .HasConstraintName("FK__Household__House__45F365D3");

                    b.HasOne("Prn212.Models.User", "User")
                        .WithMany("HouseholdMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Household__UserI__46E78A0C");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn212.Models.Log", b =>
                {
                    b.HasOne("Prn212.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Logs__UserID__4F7CD00D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn212.Models.Notification", b =>
                {
                    b.HasOne("Prn212.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__4BAC3F29");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn212.Models.Registration", b =>
                {
                    b.HasOne("Prn212.Models.User", "ApprovedByNavigation")
                        .WithMany("RegistrationApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Registrat__Appro__4316F928");

                    b.HasOne("Prn212.Models.User", "User")
                        .WithMany("RegistrationUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Registrat__UserI__4222D4EF");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn212.Models.Household", b =>
                {
                    b.Navigation("HouseholdMembers");
                });

            modelBuilder.Entity("Prn212.Models.User", b =>
                {
                    b.Navigation("HouseholdMembers");

                    b.Navigation("Households");

                    b.Navigation("Logs");

                    b.Navigation("Notifications");

                    b.Navigation("RegistrationApprovedByNavigations");

                    b.Navigation("RegistrationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
